<?php
add_action('acf/include_fields', function () {
	if (!function_exists('acf_add_local_field_group')) {
		return;
	}

	acf_add_local_field_group(array(
		'key' => 'group_674defddcbf26',
		'title' => 'Brand Featured Image',
		'fields' => array(
			array(
				'key' => 'field_674defdea7ff2',
				'label' => 'Brand Image',
				'name' => 'brand_image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => 'brand',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_65eef8ee870fc',
		'title' => 'Header/Footer Settings',
		'fields' => array(
			array(
				'key' => 'field_65eef8eecc0ff',
				'label' => 'Header Behavior',
				'name' => 'header_behavior',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'default' => 'Use Global',
					'static' => 'Static',
					'fixed' => 'Fixed',
					'sticky' => 'Sticky',
					'hide' => 'Hide',
				),
				'default_value' => 'default',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_6636eb6564175',
				'label' => 'Show Footer',
				'name' => 'show_footer',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui_on_text' => 'Show',
				'ui_off_text' => 'Hide',
				'ui' => 1,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'product',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'seamless',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_663d350c70cee',
		'title' => 'Menu Options',
		'fields' => array(
			array(
				'key' => 'field_663d350cf169a',
				'label' => 'Add sub-menu template',
				'name' => 'add_sub',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui_on_text' => 'Yes',
				'ui_off_text' => 'No',
				'ui' => 1,
			),
			array(
				'key' => 'field_663d356cf4a1f',
				'label' => 'Select Template',
				'name' => 'select_template',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_663d350cf169a',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'elementor_library',
				),
				'post_status' => '',
				'taxonomy' => array(
					0 => 'elementor_library_type:pe-menu',
				),
				'return_format' => 'object',
				'multiple' => 0,
				'allow_null' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_674ecfdf09fe3',
				'label' => 'Reveal Style',
				'name' => 'sub_reveal_style',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_663d350cf169a',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'slide' => 'Slide',
					'expand' => 'Expand',
				),
				'default_value' => 'slide',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_674eda521d08d',
				'label' => 'Overlay at hover',
				'name' => 'overlay_at_hover',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_663d350cf169a',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'allow_in_bindings' => 0,
				'ui' => 1,
				'ui_on_text' => 'Yes',
				'ui_off_text' => 'No',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'nav_menu_item',
					'operator' => '==',
					'value' => 'all',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_65eef1c6b3354',
		'title' => 'Page Settings',
		'fields' => array(
			array(
				'key' => 'field_66378fcb6ccd0',
				'label' => 'Page Layout',
				'name' => 'page_layout',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => 'You can adjust default and switched colors via "Theme Options" panel.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'layout--default' => 'Default',
					'layout--switched' => 'Switched',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_6asd6378fcb6ccd0',
				'label' => 'Header Layout',
				'name' => 'header_layout',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => 'You can adjust default and switched colors via "Theme Options" panel.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'use--global' => 'Use Global',
					'default' => 'Default',
					'switched' => 'Switched',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_65eef1c6601b6',
				'label' => 'Page Title',
				'name' => 'page_title',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui_on_text' => 'Show',
				'ui_off_text' => 'Hide',
				'ui' => 1,
			),

		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'product',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_660a7b6264d3e',
		'title' => 'Project Details',
		'fields' => array(
			array(
				'key' => 'field_660a7b62103a5',
				'label' => 'Client',
				'name' => 'client',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Leave it empty if you don\'t want to display client name.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => 'Enter client name here.',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_660a7b9bb994f',
				'label' => 'Date',
				'name' => 'date',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Leave it empty if you don\'t want to display client name.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => 'Enter project date here.',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_660a7bacb9950',
				'label' => 'Excerpt',
				'name' => 'excerpt',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => 'Leave it empty if you don\'t want to display project excerpt.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'rows' => '',
				'placeholder' => '',
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_660ab17685255',
		'title' => 'Project Featured Media',
		'fields' => array(
			array(
				'key' => 'field_660ab176740f1',
				'label' => 'Media Type',
				'name' => 'media_type',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'image' => 'Image',
					'video' => 'Video',
				),
				'default_value' => 'image',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_660ab22ff1a44',
				'label' => 'Featured Image',
				'name' => 'image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_660ab176740f1',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_660ab29e87e1b',
				'label' => 'Video Provider',
				'name' => 'video_provider',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_660ab176740f1',
							'operator' => '==',
							'value' => 'video',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'self' => 'Self hosted',
					'vimeo' => 'Vimeo',
					'youtube' => 'YouTube',
				),
				'default_value' => 'self',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_660ab2c0bf8bb',
				'label' => 'Video ID',
				'name' => 'video_id',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_660ab29e87e1b',
							'operator' => '==',
							'value' => 'vimeo',
						),
					),
					array(
						array(
							'field' => 'field_660ab29e87e1b',
							'operator' => '==',
							'value' => 'youtube',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_660ab4826a3d4',
				'label' => 'Video',
				'name' => 'self_video',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_660ab29e87e1b',
							'operator' => '==',
							'value' => 'self',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => 'mp4',
				'preview_size' => 'medium',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_660a7e121d9f2',
		'title' => 'Project Hero',
		'fields' => array(
			array(
				'key' => 'field_660a7e1209eaf',
				'label' => 'Hero Style',
				'name' => 'hero_style',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'global' => 'Use Global',
					'template' => 'Template',
					'default' => 'Default',
					'none' => 'No Hero',
				),
				'default_value' => 'global',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_660a80836b499',
				'label' => 'Select Hero Template',
				'name' => 'hero_template',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_660a7e1209eaf',
							'operator' => '==',
							'value' => 'template',
						),
					),
				),
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'elementor_library',
				),
				'post_status' => '',
				'taxonomy' => '',
				'return_format' => 'id',
				'multiple' => 0,
				'allow_null' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_662f8fb3cd670',
				'label' => 'Gallery Project',
				'name' => 'gallery_project',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
				'ui' => 1,
			),
			array(
				'key' => 'field_662f8fe585e7e',
				'label' => 'Video Project',
				'name' => 'video_project',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
				'ui' => 1,
			),
			array(
				'key' => 'field_662f92c549f59',
				'label' => 'Video Provider',
				'name' => 'ph_video_provider',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_662f8fe585e7e',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'self' => 'Self-Hosted',
					'vimeo' => 'Vimeo',
					'youtube' => 'YouTube',
				),
				'default_value' => 'self',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 1,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_662f9321ce788',
				'label' => 'Video ID',
				'name' => 'ph_video_id',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_662f92c549f59',
							'operator' => '==',
							'value' => 'vimeo',
						),
					),
					array(
						array(
							'field' => 'field_662f92c549f59',
							'operator' => '==',
							'value' => 'youtube',
						),
					),
				),
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_662f9363ce78b',
				'label' => 'Self Video',
				'name' => 'ph_self_video',
				'aria-label' => '',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_662f92c549f59',
							'operator' => '==',
							'value' => 'self',
						),
					),
				),
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => 'mp4',
			),
			array(
				'key' => 'field_662f9674de5e9',
				'label' => 'Image Gallery',
				'name' => 'image_gallery',
				'aria-label' => '',
				'type' => 'photo_gallery',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_662f8fb3cd670',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'fields[' => array(
					'edit_modal' => 'Default',
					'images_limit' => '',
					'remove_edit_button' => 'No',
					'remove_delete_button' => 'No',
				),
				'edit_modal' => 'Default',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));


	acf_add_local_field_group(array(
		'key' => 'group_66d07c66e8dae',
		'title' => 'Product Hero',
		'fields' => array(
			array(
				'key' => 'field_66d07c67eb683',
				'label' => 'Product Layout',
				'name' => 'product_layout',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'global' => 'Use Global',
					'default' => 'Theme Default',
					'custom' => 'Custom',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_66d07ca3eb684',
				'label' => 'Product Template',
				'name' => 'product_template',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_66d07c67eb683',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'elementor_library',
				),
				'post_status' => array(
					0 => 'publish',
				),
				'taxonomy' => '',
				'return_format' => 'id',
				'multiple' => 0,
				'allow_null' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'product',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_66d07d1e51570',
		'title' => 'Term Fields',
		'fields' => array(
			array(
				'key' => 'field_66d07d1ea1134',
				'label' => 'Term Color',
				'name' => 'term_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'taxonomy',
					'operator' => '!=',
					'value' => 'category',
				),
				array(
					'param' => 'taxonomy',
					'operator' => '!=',
					'value' => 'post_tag',
				),
				array(
					'param' => 'taxonomy',
					'operator' => '!=',
					'value' => 'post_format',
				),
				array(
					'param' => 'taxonomy',
					'operator' => '!=',
					'value' => 'elementor_library_type',
				),
				array(
					'param' => 'taxonomy',
					'operator' => '!=',
					'value' => 'elementor_library_category',
				),
				array(
					'param' => 'taxonomy',
					'operator' => '!=',
					'value' => 'project-categories',
				),
				array(
					'param' => 'taxonomy',
					'operator' => '!=',
					'value' => 'product_type',
				),
				array(
					'param' => 'taxonomy',
					'operator' => '!=',
					'value' => 'product_visibility',
				),
				array(
					'param' => 'taxonomy',
					'operator' => '!=',
					'value' => 'product_cat',
				),
				array(
					'param' => 'taxonomy',
					'operator' => '!=',
					'value' => 'product_tag',
				),
				array(
					'param' => 'taxonomy',
					'operator' => '!=',
					'value' => 'product_shipping_class',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_66f95b01452d9',
		'title' => 'Product Video',
		'fields' => array(
			array(
				'key' => 'field_66f95b013cc70',
				'label' => 'Product Video',
				'name' => 'product_video',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'none' => 'None',
					'self' => 'Self-Hosted',
					'vimeo' => 'Vimeo',
					'youtube' => 'Youtube',
				),
				'default_value' => 'none',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_66f95b513cc71',
				'label' => 'Self Hosted Video',
				'name' => 'self_hosted_video',
				'aria-label' => '',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_66f95b013cc70',
							'operator' => '==',
							'value' => 'self',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_66f95b6d3cc72',
				'label' => 'Video ID',
				'name' => 'video_id',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_66f95b013cc70',
							'operator' => '==',
							'value' => 'vimeo',
						),
					),
					array(
						array(
							'field' => 'field_66f95b013cc70',
							'operator' => '==',
							'value' => 'youtube',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_675d4eede4d1d',
				'label' => 'Use as featured media?',
				'name' => 'use_as_featured_media',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_66f95b013cc70',
							'operator' => '!=',
							'value' => 'none',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'allow_in_bindings' => 0,
				'ui_on_text' => 'Yes',
				'ui_off_text' => 'No',
				'ui' => 1,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'product',
				),
			),
		),
		'menu_order' => 10,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));


});

